id: I168E011E
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T23:50:55.358865'
last_modified: '2022-06-18T23:50:55.358877'
parser: null
source_metadata:
  title: Brief History of rNgog lo tsa ba Blo ldan shes rabs Tradition
  author: gser mdog paN chen shAkya mchog ldan/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2016-08-04); unrevised, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Pascale Hugon (Institute for the Cultural and Intellectual History
    of Asia, Vienna) (ph)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Pascale Hugon (ph)
  - Revisions/Corrections:Pascale Hugon (ph)
  text_witnesses: https://sakyaresearch.org/sources/1490
  bases:
    268e:
      title: Brief History of rNgog lo tsa ba Blo ldan shes rabs Tradition
      order: 1
      base_file: 268e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
